services: 
    # Mongo db service
        mongo:
                container_name: mymongo
                image: mongo:4.4-rc
                restart: always
                environment:
                        MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
                        MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
                ports: 
                - "27017:27017"
                volumes: 
                - ./mongodb-volume:/data/db

volumes:
        mongodb-volume: